### ISSUE TITLE
Unable to startup after upgrading existing setup to 0.9.59 release

### ISSUE THREAD

**Issue by DerekF35** [soulteary/docker-cronicle#24]
I updated the tag of my existing deployment to 0.9.59 and I am getting the following error.  If I force create the `install.ed` file it says the same.  I don't have a test environment setup with a scheduler, so I will work on that so that I can help provide any additional information if needed.

```
scheduler  | [1726015909.434][TRANSACTION][put] global/servers/0 ({"elapsed_ms":3.983})
scheduler  | Record successfully saved: global/servers/0
scheduler  |
scheduler  | [1726015909.44][TRANSACTION][get] global/servers/0 ({"elapsed_ms":2.252})
scheduler  | {
scheduler  |    "type": "list_page",
scheduler  |    "items": [
scheduler  |            {
scheduler  |                    "hostname": "main",
scheduler  |                    "ip": "172.18.0.5"
scheduler  |            }
scheduler  |    ]
scheduler  | }
scheduler  |
scheduler  | Docker Env Fixed.
scheduler  | [1726015909.712][2024-09-10 20:51:49][388da58b1a3f][1][Cronicle][debug][2][Cronicle v0.9.59 Starting Up][{"pid":1,"ppid":0,"node":"v18.20.4","arch":"x64","platform":"linux","argv":["/usr/local/bin/node","/opt/cronicle/bin/docker-entrypoint.js"],"execArgv":[]}]
scheduler  | [1726015909.716][2024-09-10 20:51:49][388da58b1a3f][1][Cronicle][debug][9][Writing PID File: logs/cronicled.pid: 1][]
scheduler  | [1726015909.716][2024-09-10 20:51:49][388da58b1a3f][1][Cronicle][debug][9][Confirmed PID File contents: logs/cronicled.pid: 1][]
scheduler  | [1726015909.718][2024-09-10 20:51:49][main][1][Cronicle][debug][2][Server IP: 172.18.0.5, Daemon PID: 1][]
scheduler  | [1726015909.719][2024-09-10 20:51:49][main][1][Cronicle][debug][3][Starting component: Storage][]
scheduler  | [1726015909.719][2024-09-10 20:51:49][main][1][Storage][debug][5][Setting up storage system v3.2.2][]
scheduler  | [1726015909.72][2024-09-10 20:51:49][main][1][Filesystem][debug][2][Setting up filesystem storage][]
scheduler  | [1726015909.721][2024-09-10 20:51:49][main][1][Filesystem][debug][3][Base directory: data][]
scheduler  | [1726015909.721][2024-09-10 20:51:49][main][1][Cronicle][debug][3][Starting component: WebServer][]
scheduler  | [1726015909.722][2024-09-10 20:51:49][main][1][WebServer][debug][2][pixl-server-web v2.0.2 starting up][]
scheduler  | [1726015909.727][2024-09-10 20:51:49][main][1][WebServer][debug][2][Starting HTTP server on port: 3012][]
scheduler  | [1726015909.733][2024-09-10 20:51:49][main][1][Cronicle][debug][1][Uncaught Exception: Error: ENOENT: no such file or directory, open '../conf/install.ed'][Error: ENOENT: no such file or directory, open '../conf/install.ed'     at Object.openSync (node:fs:596:3)     at writeFileSync (node:fs:2322:35)     at /opt/cronicle/bin/docker-entrypoint.js:57:13     at constructor.shutdown (/opt/cronicle/node_modules/pixl-server-storage/engines/Filesystem.js:730:3)     at /opt/cronicle/node_modules/pixl-server-storage/storage.js:1078:34     at __construct.waitForAllLocks (/opt/cronicle/node_modules/pixl-server-storage/storage.js:951:8)     at /opt/cronicle/node_modules/pixl-server-storage/storage.js:1075:9     at __construct.waitForQueueDrain (/opt/cronicle/node_modules/pixl-server-storage/storage.js:922:26)     at __construct.shutdown (/opt/cronicle/node_modules/pixl-server-storage/storage.js:1072:8)     at /opt/cronicle/bin/docker-entrypoint.js:54:19]
scheduler  | Error: ENOENT: no such file or directory, open '../conf/install.ed'
scheduler  |     at Object.openSync (node:fs:596:3)
scheduler  |     at writeFileSync (node:fs:2322:35)
scheduler  |     at /opt/cronicle/bin/docker-entrypoint.js:57:13
scheduler  |     at constructor.shutdown (/opt/cronicle/node_modules/pixl-server-storage/engines/Filesystem.js:730:3)
scheduler  |     at /opt/cronicle/node_modules/pixl-server-storage/storage.js:1078:34
scheduler  |     at __construct.waitForAllLocks (/opt/cronicle/node_modules/pixl-server-storage/storage.js:951:8)
scheduler  |     at /opt/cronicle/node_modules/pixl-server-storage/storage.js:1075:9
scheduler  |     at __construct.waitForQueueDrain (/opt/cronicle/node_modules/pixl-server-storage/storage.js:922:26)
scheduler  |     at __construct.shutdown (/opt/cronicle/node_modules/pixl-server-storage/storage.js:1072:8)
scheduler  |     at /opt/cronicle/bin/docker-entrypoint.js:54:19 {
scheduler  |   errno: -2,
scheduler  |   syscall: 'open',
scheduler  |   code: 'ENOENT',
scheduler  |   path: '../conf/install.ed'
scheduler  | }
scheduler exited with code 0
```

**Comment by soulteary** [comment]
thank you @nguyenmp 

@DerekF35 try docker pull soulteary/cronicle:0.9.63  :D

**Comment by nguyenmp** [comment]
Yay!  Thanks for merging!
