### ISSUE TITLE
issue when change storage to S3

### ISSUE THREAD

**Issue by cathy1231** [soulteary/docker-cronicle#4]
Hi!

Thanks for you docker image!

meet one issue when change storage to S3. 

```
/opt/cronicle/node_modules/pixl-server-storage/engines/S3.js:294
                this.s3.send( new S3.GetObjectCommand(params) )
                        ^

TypeError: Cannot read properties of undefined (reading 'send')
    at constructor.get (/opt/cronicle/node_modules/pixl-server-storage/engines/S3.js:294:11)
    at __construct.get (/opt/cronicle/node_modules/pixl-server-storage/storage.js:359:15)
    at /opt/cronicle/bin/docker-entrypoint.js:44:15
    at constructor.shutdown (/opt/cronicle/node_modules/pixl-server-storage/engines/S3.js:486:3)
    at /opt/cronicle/node_modules/pixl-server-storage/storage.js:1054:34
    at __construct.waitForAllLocks (/opt/cronicle/node_modules/pixl-server-storage/storage.js:927:8)
    at /opt/cronicle/node_modules/pixl-server-storage/storage.js:1051:9
    at __construct.waitForQueueDrain (/opt/cronicle/node_modules/pixl-server-storage/storage.js:898:26)
    at __construct.shutdown (/opt/cronicle/node_modules/pixl-server-storage/storage.js:1048:8)
    at /opt/cronicle/bin/docker-entrypoint.js:42:13

Node.js v18.12.1


```

**Comment by soulteary** [comment]
thanks for feedback

It may be necessary to provide a compose implementation combined with minio, this issue will be temporarily suspended until someone provides a PR, or I deal with it when I am free.
